---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: valheim
  namespace: apps
spec:
  releaseName: valheim
  chart:
    repository: https://k8s-at-home.com/charts/
    name: valheim
    version: 2.1.1
  values:
    env:
      SERVER_NAME: "The Arena Valheim"
      WORLD_NAME: "Faerun"
      SERVER_PUBLIC: False
      VPCFG_Server_enabled: True
      VPCFG_Server_enforceMod: False
      VPCFG_Server_dataRate: 600
      TZ: "Australia/Sydney"

      VALHEIM_PLUS: true
      VPCFG_Server_enabled: true
      VPCFG_Server_enforceMod: false
      VPCFG_Server_dataRate: 600
      # Don't log duplicate lines
      BEPINEXCFG_Logging_DOT_Console_WriteUnityLog: False

      # Set in Secrets:
      # SERVER_PASS
      # DISCORD_WEBHOOK

      # Notify when shutting down
      DISCORD_PRESHUTDOWN_MESSAGE: Server is SHUTTING DOWN!
      PRE_SERVER_SHUTDOWN_HOOK: 'curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$DISCORD_PRESHUTDOWN_MESSAGE\"}" "$DISCORD_WEBHOOK"'

      # Notify when the server is about to restart
      DISCORD_PRERESTART_MESSAGE: Server is RESTARTING in one minute!"
      PRE_RESTART_HOOK: 'curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$DISCORD_PRERESTART_MESSAGE\"}" "$DISCORD_WEBHOOK" && sleep 60'

      # Notify when the server restarts
      DISCORD_POSTRESTART_MESSAGE: Server is RESTARTED!
      POST_RESTART_HOOK: 'curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$DISCORD_POSTRESTART_MESSAGE\"}" "$DISCORD_WEBHOOK"'

      # Notify when the start starts
      DISCORD_POSTSTART_MESSAGE: Server is STARTED!
      POST_START_HOOK: 'curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$DISCORD_POSTSTART_MESSAGE\"}" "$DISCORD_WEBHOOK"'

      # Notify when someone logs in
      VALHEIM_LOG_FILTER_CONTAINS_Spawned: "Got character ZDOID from"
      ON_VALHEIM_LOG_FILTER_CONTAINS_Spawned: '{ read l; l=${l//*ZDOID from /}; l=${l// :*/}; msg="Player $l spawned into the world"; curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$msg\"}" "$DISCORD_WEBHOOK"; }'

    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: 10.71.100.3
    persistence:
      config:
        storageClass: "gluster-heketi"
        accessMode: ReadWriteOnce
        enabled: true
        size: 10Gi
        resources:
      requests:
        memory: 2048Mi
        cpu: 300m
      limits:
        memory: 4096Mi
  valuesFrom:
  - secretKeyRef:
      name: valheim-secrets
