---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: valheim
  namespace: apps
spec:
  releaseName: valheim
  chart:
    repository: https://k8s-at-home.com/charts/
    name: valheim
    version: 2.1.1
  values:
    env:
      SERVER_NAME: "Meme Babies"
      WORLD_NAME: "MemeWorld"
      SERVER_PUBLIC: False
      VALHEIM_PLUS: true
      VPCFG_Server_enabled: True
      VPCFG_Server_enforceMod: True
      VPCFG_Server_dataRate: 600
      VPCFG_Server_serverSyncsConfig: True
      VPCFG_Server_serverSyncHotkeys: True

      VPCFG_AdvancedBuildingMode_enabled: True
      VPCFG_AdvancedBuildingMode_copyObjectRotation: Comma
      VPCFG_AdvancedBuildingMode_pasteObjectRotation: Period
      VPCFG_AdvancedBuildingMode_increaseScrollSpeed: PageUp
      VPCFG_AdvancedBuildingMode_decreaseScrollSpeed: PageDown

      VPCFG_AdvancedEditingMode_enabled: True
      VPCFG_AdvancedEditingMode_confirmPlacementOfAdvancedEditingMode: End
      VPCFG_AdvancedEditingMode_copyObjectRotation: Comma
      VPCFG_AdvancedEditingMode_pasteObjectRotation: Period
      VPCFG_AdvancedEditingMode_increaseScrollSpeed: PageUp
      VPCFG_AdvancedEditingMode_decreaseScrollSpeed: PageDown

      VPCFG_GridAlignment_enabled: True
      VPCFG_GridAlignment_align: LeftAlt
      VPCFG_GridAlignment_alignToggle: F7
      VPCFG_GridAlignment_changeDefaultAlignment: F6

      VPCFG_Map_enabled: True
      VPCFG_Map_shareMapProgression: True
      VPCFG_Map_preventPlayerFromTurningOffPublicPosition: True
      VPCFG_Map_shareablePins: True
      VPCFG_Map_showCartsAndBoats: True

      VPCFG_Building_enabled: True
      VPCFG_Building_enableAreaRepair: True

      VPCFG_CraftFromChest_enable: True
      VPCFG_CraftFromChest_checkFromWorkbench: True

      VPCFG_Player_enable: True
      VPCFG_Player_baseAutoPickUpRange: 4
      VPCFG_Player_cropNotifier: True
      VPCFG_Player_autoRepair: True

      VPCFG_GameClock_enabled: True

      VPCFG_Hud_enabled: True
      VPCFG_Hud_showRequiredItems: True
      VPCFG_Hud_displayBowAmmoCounts: 1

      VPCFG_FireSource_enable: True
      VPCFG_FireSource_torches: true

      VPCFG_Workbench_enabled: True
      VPCFG_workbenchRange: 40

      VPCFG_Smelter_enabled: True
      VPCFG_Smelter_autoDeposit: True
      VPCFG_Smelter_autoFuel: True
      VPCFG_Smelter_autoRange: 5

      VPCFG_Furnace_enabled: True
      VPCFG_Furnace_autoDeposit: True
      VPCFG_Furnace_autoFuel: True
      VPCFG_Furnace_autoRange: 5

      VPCFG_Kiln_enabled: True
      VPCFG_Kiln_autoDeposit: True
      VPCFG_Kiln_autoFuel: True
      VPCFG_Kiln_autoRange: 5
      VPCFG_Kiln_stopAutoFuelThreshold: 100

      VPCFG_SpinningWheel_enabled: True
      VPCFG_SpinningWheel_autoDeposit: True
      VPCFG_SpinningWheel_autoFuel: True
      VPCFG_SpinningWheel_autoRange: 5

      VPCFG_Windmill_enabled: True
      VPCFG_Windmill_autoDeposit: True
      VPCFG_Windmill_autoFuel: True
      VPCFG_Windmill_autoRange: 5

      VPCFG_Fermenter_enabled: True
      VPCFG_Fermenter_showDuration: True
      VPCFG_Fermenter_autoDeposit: True
      VPCFG_Fermenter_autoFuel: True
      VPCFG_Fermenter_autoRange: 5

      VPCFG_Beehive_enabled: True
      VPCFG_Beehive_showDuration: True
      VPCFG_Beehive_autoDeposit: True
      VPCFG_Beehive_autoFuel: True
      VPCFG_Beehive_autoRange: 5

      TZ: "Australia/Sydney"

      # Don't log duplicate lines
      BEPINEXCFG_Logging_DOT_Console_WriteUnityLog: False

      # Set in Secrets:
      # SERVER_PASS
      # DISCORD_WEBHOOK

      # Notify when shutting down
      DISCORD_PRESHUTDOWN_MESSAGE: Server is SHUTTING DOWN!
      PRE_SERVER_SHUTDOWN_HOOK: 'curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$DISCORD_PRESHUTDOWN_MESSAGE\"}" "$DISCORD_WEBHOOK"'

      # Notify when the server is about to restart
      DISCORD_PRERESTART_MESSAGE: Server is RESTARTING in one minute!"
      PRE_RESTART_HOOK: 'curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$DISCORD_PRERESTART_MESSAGE\"}" "$DISCORD_WEBHOOK" && sleep 60'

      # Notify when the server restarts
      DISCORD_POSTRESTART_MESSAGE: Server is RESTARTED!
      POST_RESTART_HOOK: 'curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$DISCORD_POSTRESTART_MESSAGE\"}" "$DISCORD_WEBHOOK"'

      # Notify when the start starts
      DISCORD_POSTSTART_MESSAGE: Server is STARTED!
      POST_START_HOOK: 'curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$DISCORD_POSTSTART_MESSAGE\"}" "$DISCORD_WEBHOOK"'

      # Notify when someone logs in
      VALHEIM_LOG_FILTER_CONTAINS_Spawned: "Got character ZDOID from"
      ON_VALHEIM_LOG_FILTER_CONTAINS_Spawned: '{ read l; l=${l//*ZDOID from /}; l=${l// :*/}; msg="Player $l spawned into the world"; curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$msg\"}" "$DISCORD_WEBHOOK"; }'

    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: 10.71.100.3
    persistence:
      config:
        storageClass: "gluster-heketi"
        accessMode: ReadWriteOnce
        enabled: true
        size: 10Gi
        resources:
    requests:
      memory: 2048Mi
      cpu: 300m
    limits:
      memory: 4096Mi
  valuesFrom:
  - secretKeyRef:
      name: valheim-secrets
