---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
spec:
  releaseName: nzbget
  chart:
    repository: https://k8s-at-home.com/charts/
    name: nzbget
    version: 9.1.1
  values:
    image:
      repository: linuxserver/nzbget
      tag: version-v21.0
    ingress:
      enabled: true
    env:
      TZ: "Australia/Sydney"
    persistence:
      config:
        storageClass: "gluster-heketi"
        accessMode: ReadWriteOnce
        enabled: true
        size: 2Gi
      downloads:
        enabled: true
        existingClaim: "nfs-media-downloads-pvc"
      media:
        enabled: true
        existingClaim: "nfs-media-pvc"
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 800Mi
  valuesFrom:
  - configMapKeyRef:
      name: nzbget-ingress
