apiVersion: v1
kind: Service
metadata:
  name: guacamole
  namespace: apps
  labels:
    app.kubernetes.io/name: guacamole
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: guacamole-guacamole
