apiVersion: v1
kind: Service
metadata:
  name: guacd
  namespace: apps
  labels:
    app.kubernetes.io/name: guacamole
spec:
  type: ClusterIP
  ports:
    - port: 4822
      targetPort: guacd
      protocol: TCP
      name: guacd
  selector:
    app.kubernetes.io/name: guacamole-guacd
