---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  releaseName: grafana
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: grafana
    version: 5.0.5
  values:
    ingress:
      enabled: true

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

    grafana.ini:
      auth:
        disable_login_form: true
        disable_signout_menu: true
      alerting:
        enabled: false
      auth.anonymous:
        enabled: true
        org_role: Editor

    sidecar:
      dashboards:
        enabled: true
      datasources:
        enabled: true

  valuesFrom:
  - configMapKeyRef:
      name: grafana-ingress