---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  releaseName: radarr
  chart:
    repository: https://k8s-at-home.com/charts/
    name: radarr
    version: 10.1.1
  values:
    image:
      repository: linuxserver/radarr
      tag: 3.0.2.4552-ls97
    ingress:
      enabled: true
    env:
      TZ: "Australia/Sydney"
    persistence:
      config:
        storageClass: "gluster-heketi"
        accessMode: ReadWriteOnce
        enabled: true
        size: 2Gi
      downloads:
        enabled: true
        existingClaim: "nfs-media-downloads-pvc"
      media:
        enabled: true
        existingClaim: "nfs-media-pvc"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
  valuesFrom:
  - configMapKeyRef:
      name: radarr-ingress
