---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-pv
  namespace: media
spec:
  storageClassName: media
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 4Ti
  nfs:
    path: /data/media
    server: 10.71.6.4
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-pvc
  namespace: media
spec:
  storageClassName: media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
