---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-downloads-pvc
  namespace: media
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
