---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  releaseName: sonarr
  chart:
    repository: https://k8s-at-home.com/charts/
    name: sonarr
    version: 10.1.1
  values:
    image:
      repository: linuxserver/sonarr
      tag: version-3.0.6.1265
    ingress:
      enabled: true
    env:
      TZ: "Australia/Sydney"
    persistence:
      config:
        enabled: true
        storageClass: "gluster-heketi"
        accessMode: ReadWriteOnce
        size: 2Gi
      media:
        enabled: true
        existingClaim: "nfs-media-pvc"
      downloads:
        enabled: true
        existingClaim: "nfs-media-downloads-pvc"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
  valuesFrom:
  - configMapKeyRef:
      name: sonarr-ingress
