---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux-private
  namespace: fluxcd
spec:
  releaseName: flux-private
  chart:
    repository: https://charts.fluxcd.io
    name: flux
    version: 1.6.2
  values:
    git:
      url: "git@github.com:AaronFoley/homelab-k8s-private.git"
    registry:
      disableScanning: true
