---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  releaseName: plex
  chart:
    git: https://github.com/munnerz/kube-plex
    ref: master
    path: charts/kube-plex
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.20.3.3483-211702a9f
    kubePlex:
      enabled: false
    ingress:
      enabled: True
      annotations:
        nginx.ingress.kubernetes.io/enable-global-auth: "false"
    timezone: "Australia/Sydney"
    persistence:
      transcode:
        enabled: true
        storageClass: "nfs-client"
        accessMode: ReadWriteOnce
        size: 50Gi
      data:
        enabled: true
        claimName: nfs-media-pvc
      config:
        storageClass: "gluster-heketi"
        accessMode: ReadWriteOnce
        size: 20Gi
    resources:
      limits:
        gpu.intel.com/i915: 1
        memory: 4900Mi
      requests:
        cpu: 35m
        memory: 1500Mi
  valuesFrom:
  - secretKeyRef:
      name: plex-secrets
  - configMapKeyRef:
      name: plex-ingress
