---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: postgres
  namespace: apps
spec:
  releaseName: postgres
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: postgresql
    version: 10.2.0
  values:
    existingSecret: postgres-secrets
    persistence:
      enabled: true
      storageClass: gluster-heketi
      size: 20Gi
