---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: monica
  namespace: apps
spec:
  releaseName: monica
  chart:
    repository: https://k8s-at-home.com/charts/
    name: monica
    version: 4.2.0
  values:
    image:
      tag: 3.0.1-apache
    envFrom:
      - secretRef:
          name: monica-secrets
    additionalContainers:
      - name: monica-cron
        image: monica:3.0.1-apache
        volumeMounts:
          - name: config
            mountPath: /var/www/html/storage
        envFrom:
        - secretRef:
            name: monica-secrets
        args: ['cron.sh']
      - name: monica-queue
        image: monica:3.0.1-apache
        volumeMounts:
          - name: config
            mountPath: /var/www/html/storage
        envFrom:
        - secretRef:
            name: monica-secrets
        args: ['queue.sh']
    persistence:
      config:
        storageClass: "gluster-heketi"
        accessMode: ReadWriteMany
        enabled: true
        size: 5Gi
    ingress:
      enabled: true
  valuesFrom:
  - configMapKeyRef:
      name: monica-ingress
