---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: unifi
  namespace: infra
spec:
  releaseName: unifi
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 0.10.0
    name: unifi
  values:
    controllerService:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
      loadBalancerIP: 10.71.100.2
    discoveryService:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
      loadBalancerIP: 10.71.100.2
    stunService:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
      loadBalancerIP: 10.71.100.2
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  valuesFrom:
  - configMapKeyRef:
      name: unifi-ingress
