apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag
  namespace: apps
  labels:
    app.kubernetes.io/name: wallabag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
  storageClassName: gluster-heketi
