apiVersion: v1
kind: Service
metadata:
  name: wallabag
  namespace: apps
  labels:
    app.kubernetes.io/name: wallabag
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: wallabag
