---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
spec:
  keys:
    - api-key
  path: k8s/cert-manager/cloudflare-api-key
  type: Opaque
